### PR TITLE
Add GCC and LLVM to OMP Landscape

### PR DESCRIPTION
**Pull request by edelsohn**
This pull request adds logos and references to GCC and LLVM in the OMP Landscape page.  Hopefully the formatting, style, and choice of section are correct.

### CODE REVIEW

**Comment by edelsohn** [comment]
Thanks for adding the Twitter references.

Swift is controlled by Apple.  LLVM is controlled by the LLVM Foundation, but there is no Crunchbase reference.  Chris Lattner (the creator of LLVM) now works for Google and Google contributes more to LLVM than Apple.

**Comment by dankohn** [comment]
I created an entry for LLVM Foundation. Please LGTM if this now looks good to you. I'll be replacing the LLVM logo tomorrow with one that says `LLVM` under it.

**Comment by edelsohn** [comment]
Dan, I am a member of the GCC Steering Committee.  The GNU Toolchain is under the auspices of the GNU Project.  The FSF and the GNU Project are entangled with each other.

**Comment by dankohn** [comment]
@edelsohn I promise you that I don't want to get involved in any GNU/FSF politics. However, the standard we have used is from [New Entries](https://github.com/openmainframeproject/omp-landscape/#new-entries) where we say `Crunchbase organization should be the company or organization that controls the software. That is normally the owner of the trademark, whether or not a trademark has been formally filed.`

My understand is that FSF owns the trademark for GNU: http://tsdr.uspto.gov/#caseNumber=85380218&caseType=SERIAL_NO&searchType=statusSearch

That said, it's up to @jmertic to make the ultimate decision for the OMP Landscape.

**Pull request merged**
