### PR TITLE
Fix Zowe Conformance layout

### PR DESCRIPTION
**Pull request by jmertic**

### CODE REVIEW

**Comment by AndreyKozlov1984** [comment]
Then I will put one logo to the left of every category where it is possible!

**Comment by jmertic** [comment]
Oooh - you have me hooked now on the clickable one LOL.

If we could have the box with rounded edges then that would be amazing. Or a transparent background. But neither are showstoppers.

Thank you!!!

**Comment by AndreyKozlov1984** [comment]
@jmertic please check!

**Comment by AndreyKozlov1984** [comment]
https://deploy-preview-434--omp-landscape.netlify.app/zowe-conformant

**Comment by jmertic** [comment]
Looks great! Two minor issues...

1) Looking at this view ( https://deploy-preview-434--omp-landscape.netlify.app/fullscreen/zowe-conformant ) there is a blue box to the right of the image. Not sure if that's a wierd artifact or something
2) If you go to https://deploy-preview-434--omp-landscape.netlify.app/zowe-conformant and then go to another tab, the images are still showing.

**Comment by AndreyKozlov1984** [comment]
Ok, I'll need to update a landscapeapp to fix this issues,  I am really curious what is the reason for these artifacts

**Comment by jmertic** [comment]
Awesome! One minor bit - see the blue bar on the top row logo...
Screen Shot 2022-05-09 at 2 54 29 PM

**Comment by AndreyKozlov1984** [comment]
Yep, fixing it right now, that was my test code.

**Comment by AndreyKozlov1984** [comment]
@jmertic finally this should work!

**Comment by jmertic** [comment]
This is awesome - thank you @AndreyKozlov1984 !

**Pull request merged**
