### PR TITLE
Add OpenBLAS

### PR DESCRIPTION
**Pull request by edelsohn**
I'm not certain what to list for crunchbase record for OpenBLAS.

I think that you need to cherry-pick the openblas changes because the pull request seems to include the earlier commits from the main repo that I pulled to get back into sync for this new pull request.

### CODE REVIEW

**Comment by dankohn** [comment]
I created a new nonprofit Crunchbase entry for OpenBLAS. Going forward, you want to sync your fork with the upstream repo and then do these submissions on a branch of your fork to avoid conflicts.

**Comment by edelsohn** [comment]
Thanks for merging it. I specifically pulled the OMP head into my fork before creating the new pull request. Github did something strange with the pull and merge into my fork initiated on the web interface.

**Comment by dankohn** [comment]
Right. The issue is that we squash commits so your master now differs from upstream master. That's what you want to make submissions off of a branch, so you can just delete it when it's merged and then resync your master to the upstream master.

**Comment by dankohn** [comment]
Also, I haven't merged. @jmertic owns the landscape. @edelsohn please add an LGTM if it does to you:

https://deploy-preview-9--omp-landscape.netlify.com/selected=open-blas

**Comment by edelsohn** [comment]
LGTM. I'll defer to you two on the final decisions.

**Pull request merged**
